// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b21ca848-c489-4657-b778-f87fb99454f5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_fMW8fwYIz",
    "aws_user_pools_web_client_id": "64teiqhp3ip5q67k7ud1gde3qk",
    "oauth": {},
    "aws_mobile_analytics_app_id": "3122613db3264763983c3b94e59ebb2d",
    "aws_mobile_analytics_app_region": "us-west-2",
    "XR": {
        "scenes": {
            "demo": {
                "sceneConfig": {
                    "sceneId": "aecd5ba977214a3aa1cea6d7375d3ad0.scene",
                    "region": "us-west-2",
                    "projectName": "Lucky-Money",
                    "url": "https://sumerian.us-west-2.amazonaws.com/20180801/projects/Lucky-Money/release/authTokens?sceneId=aecd5ba977214a3aa1cea6d7375d3ad0.scene"
                }
            },
            "LuckyMoneyXIN": {
                "sceneConfig": {
                    "sceneId": "3c3ab932a21842e7bda8bd40209966c5.scene",
                    "region": "us-west-2",
                    "projectName": "Lucky-Money",
                    "url": "https://sumerian.us-west-2.amazonaws.com/20180801/projects/Lucky-Money/release/authTokens?sceneId=3c3ab932a21842e7bda8bd40209966c5.scene"
                }
            }
        }
    }
};


export default awsmobile;
